/* Generated By:JavaCC: Do not edit this line. compiConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface compiConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int OP_ARITMETICO = 6;
  /** RegularExpression Id. */
  int OP_RELACIONAL = 7;
  /** RegularExpression Id. */
  int OP_LOGICO = 8;
  /** RegularExpression Id. */
  int OP_ASIGNACION = 9;
  /** RegularExpression Id. */
  int OP_INCREMENTO = 10;
  /** RegularExpression Id. */
  int OP_TERNARIO = 11;
  /** RegularExpression Id. */
  int OP_FUSION_NULA = 12;
  /** RegularExpression Id. */
  int OP_BIT = 13;
  /** RegularExpression Id. */
  int APUNTADOR = 14;
  /** RegularExpression Id. */
  int DELIMITADOR = 15;
  /** RegularExpression Id. */
  int PUNTUACION = 16;
  /** RegularExpression Id. */
  int CONTROL_CONDICIONAL = 17;
  /** RegularExpression Id. */
  int CONTROL_BUCLES = 18;
  /** RegularExpression Id. */
  int CONTROL_EXCEPCIONES = 19;
  /** RegularExpression Id. */
  int DECLARACION_VAR = 20;
  /** RegularExpression Id. */
  int TIPOS_DATO = 21;
  /** RegularExpression Id. */
  int VALORES = 22;
  /** RegularExpression Id. */
  int POO_CLASES = 23;
  /** RegularExpression Id. */
  int POO_MIEMBROS = 24;
  /** RegularExpression Id. */
  int POO_MODIFICADORES = 25;
  /** RegularExpression Id. */
  int FUNCIONES = 26;
  /** RegularExpression Id. */
  int ARCHIVOS = 27;
  /** RegularExpression Id. */
  int ENTRADA_SALIDA = 28;
  /** RegularExpression Id. */
  int COLECCIONES = 29;
  /** RegularExpression Id. */
  int OPERACIONES_COL = 30;
  /** RegularExpression Id. */
  int CONCURRENCIA = 31;
  /** RegularExpression Id. */
  int MATH_MODULO = 32;
  /** RegularExpression Id. */
  int FUNC_MATEMATICAS = 33;
  /** RegularExpression Id. */
  int ALEATORIO = 34;
  /** RegularExpression Id. */
  int ESPECIALES = 35;
  /** RegularExpression Id. */
  int NUMERO = 36;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 37;
  /** RegularExpression Id. */
  int COMILLAS = 38;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"\\t\"",
    "<OP_ARITMETICO>",
    "<OP_RELACIONAL>",
    "<OP_LOGICO>",
    "<OP_ASIGNACION>",
    "<OP_INCREMENTO>",
    "\"?:\"",
    "\"??\"",
    "\"~\"",
    "<APUNTADOR>",
    "<DELIMITADOR>",
    "<PUNTUACION>",
    "<CONTROL_CONDICIONAL>",
    "<CONTROL_BUCLES>",
    "<CONTROL_EXCEPCIONES>",
    "<DECLARACION_VAR>",
    "<TIPOS_DATO>",
    "<VALORES>",
    "<POO_CLASES>",
    "<POO_MIEMBROS>",
    "<POO_MODIFICADORES>",
    "<FUNCIONES>",
    "<ARCHIVOS>",
    "<ENTRADA_SALIDA>",
    "<COLECCIONES>",
    "<OPERACIONES_COL>",
    "<CONCURRENCIA>",
    "\"Math\"",
    "<FUNC_MATEMATICAS>",
    "<ALEATORIO>",
    "<ESPECIALES>",
    "<NUMERO>",
    "<IDENTIFICADOR>",
    "<COMILLAS>",
  };

}
