/* Generated By:JavaCC: Do not edit this line. compi.java */
import java.io.*;

public class compi implements compiConstants {
  public static void main(String[] args) throws ParseException {
    InputStream inputStream = System.in; // Por defecto usa stdin

    if (args.length > 0) {
      try {
        inputStream = new FileInputStream(args[0]);
      } catch (FileNotFoundException e) {
        System.out.println("Error: Archivo no encontrado - " + args[0]);
        return;
      }
    } else {
      System.out.println("Leyendo desde la entrada est\u00e1ndar...");
    }

    try {
      compi analizador = new compi(inputStream);
      analizador.Inicio();
      System.out.println("\u005ctTermino el analisis");
      System.out.println("\u005ctAnalisis exitoso");
    } catch (ParseException e) {
      System.out.println("\u005ctSe encontraron errores en el analisis");
      System.out.println(e.getMessage());
    }
  }

  static final public void Inicio() throws ParseException {
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case OP_ARITMETICO:
      case OP_RELACIONAL:
      case OP_LOGICO:
      case OP_ASIGNACION:
      case OP_INCREMENTO:
      case OP_TERNARIO:
      case OP_FUSION_NULA:
      case OP_BIT:
      case APUNTADOR:
      case DELIMITADOR:
      case PUNTUACION:
      case CONTROL_CONDICIONAL:
      case CONTROL_BUCLES:
      case CONTROL_EXCEPCIONES:
      case DECLARACION_VAR:
      case TIPOS_DATO:
      case VALORES:
      case POO_CLASES:
      case POO_MIEMBROS:
      case POO_MODIFICADORES:
      case FUNCIONES:
      case ARCHIVOS:
      case ENTRADA_SALIDA:
      case COLECCIONES:
      case OPERACIONES_COL:
      case CONCURRENCIA:
      case MATH_MODULO:
      case FUNC_MATEMATICAS:
      case ALEATORIO:
      case ESPECIALES:
      case NUMERO:
      case IDENTIFICADOR:
      case COMILLAS:
        ;
        break;
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case OP_ARITMETICO:
        jj_consume_token(OP_ARITMETICO);
        break;
      case OP_RELACIONAL:
        jj_consume_token(OP_RELACIONAL);
        break;
      case OP_LOGICO:
        jj_consume_token(OP_LOGICO);
        break;
      case OP_ASIGNACION:
        jj_consume_token(OP_ASIGNACION);
        break;
      case OP_INCREMENTO:
        jj_consume_token(OP_INCREMENTO);
        break;
      case OP_TERNARIO:
        jj_consume_token(OP_TERNARIO);
        break;
      case OP_FUSION_NULA:
        jj_consume_token(OP_FUSION_NULA);
        break;
      case OP_BIT:
        jj_consume_token(OP_BIT);
        break;
      case APUNTADOR:
        jj_consume_token(APUNTADOR);
        break;
      case DELIMITADOR:
        jj_consume_token(DELIMITADOR);
        break;
      case PUNTUACION:
        jj_consume_token(PUNTUACION);
        break;
      case CONTROL_CONDICIONAL:
        jj_consume_token(CONTROL_CONDICIONAL);
        break;
      case CONTROL_BUCLES:
        jj_consume_token(CONTROL_BUCLES);
        break;
      case CONTROL_EXCEPCIONES:
        jj_consume_token(CONTROL_EXCEPCIONES);
        break;
      case DECLARACION_VAR:
        jj_consume_token(DECLARACION_VAR);
        break;
      case TIPOS_DATO:
        jj_consume_token(TIPOS_DATO);
        break;
      case VALORES:
        jj_consume_token(VALORES);
        break;
      case POO_CLASES:
        jj_consume_token(POO_CLASES);
        break;
      case POO_MIEMBROS:
        jj_consume_token(POO_MIEMBROS);
        break;
      case POO_MODIFICADORES:
        jj_consume_token(POO_MODIFICADORES);
        break;
      case FUNCIONES:
        jj_consume_token(FUNCIONES);
        break;
      case ARCHIVOS:
        jj_consume_token(ARCHIVOS);
        break;
      case ENTRADA_SALIDA:
        jj_consume_token(ENTRADA_SALIDA);
        break;
      case COLECCIONES:
        jj_consume_token(COLECCIONES);
        break;
      case OPERACIONES_COL:
        jj_consume_token(OPERACIONES_COL);
        break;
      case CONCURRENCIA:
        jj_consume_token(CONCURRENCIA);
        break;
      case MATH_MODULO:
        jj_consume_token(MATH_MODULO);
        break;
      case FUNC_MATEMATICAS:
        jj_consume_token(FUNC_MATEMATICAS);
        break;
      case ALEATORIO:
        jj_consume_token(ALEATORIO);
        break;
      case ESPECIALES:
        jj_consume_token(ESPECIALES);
        break;
      case COMILLAS:
        jj_consume_token(COMILLAS);
        break;
      case NUMERO:
        jj_consume_token(NUMERO);
        break;
      case IDENTIFICADOR:
        jj_consume_token(IDENTIFICADOR);
        break;
      default:
        jj_la1[1] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    jj_consume_token(0);
  }

  static private boolean jj_initialized_once = false;
  /** Generated Token Manager. */
  static public compiTokenManager token_source;
  static SimpleCharStream jj_input_stream;
  /** Current token. */
  static public Token token;
  /** Next token. */
  static public Token jj_nt;
  static private int jj_ntk;
  static private int jj_gen;
  static final private int[] jj_la1 = new int[2];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0xffffffc0,0xffffffc0,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0x7f,0x7f,};
   }

  /** Constructor with InputStream. */
  public compi(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public compi(java.io.InputStream stream, String encoding) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser.  ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new compiTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 2; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 2; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public compi(java.io.Reader stream) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new compiTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 2; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  static public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 2; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public compi(compiTokenManager tm) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 2; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(compiTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 2; i++) jj_la1[i] = -1;
  }

  static private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }


/** Get the next Token. */
  static final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  static final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  static private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  static private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  static private int[] jj_expentry;
  static private int jj_kind = -1;

  /** Generate ParseException. */
  static public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[39];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 2; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 39; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  static final public void enable_tracing() {
  }

  /** Disable tracing. */
  static final public void disable_tracing() {
  }

}
