/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package com.lexico.analizador;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LEFT_SHIFT_ASSIGN = 5;
  /** RegularExpression Id. */
  int RIGHT_SHIFT_ASSIGN = 6;
  /** RegularExpression Id. */
  int POW_ASSIGN = 7;
  /** RegularExpression Id. */
  int PLUS_ASSIGN = 8;
  /** RegularExpression Id. */
  int MINUS_ASSIGN = 9;
  /** RegularExpression Id. */
  int MULT_ASSIGN = 10;
  /** RegularExpression Id. */
  int DIV_ASSIGN = 11;
  /** RegularExpression Id. */
  int MOD_ASSIGN = 12;
  /** RegularExpression Id. */
  int AND_ASSIGN = 13;
  /** RegularExpression Id. */
  int OR_ASSIGN = 14;
  /** RegularExpression Id. */
  int XOR_ASSIGN = 15;
  /** RegularExpression Id. */
  int ASSIGN = 16;
  /** RegularExpression Id. */
  int POW = 17;
  /** RegularExpression Id. */
  int INT_DIV = 18;
  /** RegularExpression Id. */
  int PLUS = 19;
  /** RegularExpression Id. */
  int MINUS = 20;
  /** RegularExpression Id. */
  int DIV = 21;
  /** RegularExpression Id. */
  int MOD = 22;
  /** RegularExpression Id. */
  int INCREMENT = 23;
  /** RegularExpression Id. */
  int DECREMENT = 24;
  /** RegularExpression Id. */
  int STRICT_EQ = 25;
  /** RegularExpression Id. */
  int STRICT_NEQ = 26;
  /** RegularExpression Id. */
  int LE = 27;
  /** RegularExpression Id. */
  int GE = 28;
  /** RegularExpression Id. */
  int EQ = 29;
  /** RegularExpression Id. */
  int NEQ = 30;
  /** RegularExpression Id. */
  int LEFT_SHIFT = 31;
  /** RegularExpression Id. */
  int UNSIGNED_SHIFT = 32;
  /** RegularExpression Id. */
  int RIGHT_SHIFT = 33;
  /** RegularExpression Id. */
  int LT = 34;
  /** RegularExpression Id. */
  int GT = 35;
  /** RegularExpression Id. */
  int AND = 36;
  /** RegularExpression Id. */
  int OR = 37;
  /** RegularExpression Id. */
  int NOT = 38;
  /** RegularExpression Id. */
  int BIT_XOR = 39;
  /** RegularExpression Id. */
  int BIT_NOT = 40;
  /** RegularExpression Id. */
  int NULL_COALESCE = 41;
  /** RegularExpression Id. */
  int NULL_SAFE = 42;
  /** RegularExpression Id. */
  int RANGE_INCL = 43;
  /** RegularExpression Id. */
  int RANGE = 44;
  /** RegularExpression Id. */
  int TERNARY = 45;
  /** RegularExpression Id. */
  int COLON = 46;
  /** RegularExpression Id. */
  int PIPE = 47;
  /** RegularExpression Id. */
  int DOT = 48;
  /** RegularExpression Id. */
  int COMMA = 49;
  /** RegularExpression Id. */
  int SEMICOLON = 50;
  /** RegularExpression Id. */
  int DOUBLE_SEMICOLON = 51;
  /** RegularExpression Id. */
  int UNDERSCORE = 52;
  /** RegularExpression Id. */
  int LPAREN = 53;
  /** RegularExpression Id. */
  int RPAREN = 54;
  /** RegularExpression Id. */
  int LBRACE = 55;
  /** RegularExpression Id. */
  int RBRACE = 56;
  /** RegularExpression Id. */
  int LBRACKET = 57;
  /** RegularExpression Id. */
  int RBRACKET = 58;
  /** RegularExpression Id. */
  int INT8 = 59;
  /** RegularExpression Id. */
  int INT16 = 60;
  /** RegularExpression Id. */
  int INT32 = 61;
  /** RegularExpression Id. */
  int INT64 = 62;
  /** RegularExpression Id. */
  int UINT8 = 63;
  /** RegularExpression Id. */
  int UINT16 = 64;
  /** RegularExpression Id. */
  int UINT32 = 65;
  /** RegularExpression Id. */
  int UINT64 = 66;
  /** RegularExpression Id. */
  int FLOAT32 = 67;
  /** RegularExpression Id. */
  int FLOAT64 = 68;
  /** RegularExpression Id. */
  int INTEGER = 69;
  /** RegularExpression Id. */
  int NUMBER = 70;
  /** RegularExpression Id. */
  int DECIMAL = 71;
  /** RegularExpression Id. */
  int DOUBLE = 72;
  /** RegularExpression Id. */
  int CHAR = 73;
  /** RegularExpression Id. */
  int RUNE = 74;
  /** RegularExpression Id. */
  int BYTE = 75;
  /** RegularExpression Id. */
  int STRING = 76;
  /** RegularExpression Id. */
  int BOOLEAN = 77;
  /** RegularExpression Id. */
  int ANY = 78;
  /** RegularExpression Id. */
  int VOID = 79;
  /** RegularExpression Id. */
  int NULL = 80;
  /** RegularExpression Id. */
  int UNDEFINED = 81;
  /** RegularExpression Id. */
  int NEVER = 82;
  /** RegularExpression Id. */
  int UNKNOWN = 83;
  /** RegularExpression Id. */
  int NONE = 84;
  /** RegularExpression Id. */
  int TRUE = 85;
  /** RegularExpression Id. */
  int FALSE = 86;
  /** RegularExpression Id. */
  int ARRAY = 87;
  /** RegularExpression Id. */
  int LIST = 88;
  /** RegularExpression Id. */
  int TUPLE = 89;
  /** RegularExpression Id. */
  int MAP = 90;
  /** RegularExpression Id. */
  int DICT = 91;
  /** RegularExpression Id. */
  int OBJECT = 92;
  /** RegularExpression Id. */
  int RECORD = 93;
  /** RegularExpression Id. */
  int STRUCT = 94;
  /** RegularExpression Id. */
  int ENUM = 95;
  /** RegularExpression Id. */
  int INTERFACE = 96;
  /** RegularExpression Id. */
  int CLASS = 97;
  /** RegularExpression Id. */
  int PUBLIC = 98;
  /** RegularExpression Id. */
  int PRIVATE = 99;
  /** RegularExpression Id. */
  int PROTECTED = 100;
  /** RegularExpression Id. */
  int INTERNAL = 101;
  /** RegularExpression Id. */
  int READONLY = 102;
  /** RegularExpression Id. */
  int WRITEONLY = 103;
  /** RegularExpression Id. */
  int FRIEND = 104;
  /** RegularExpression Id. */
  int PACKAGE_VIS = 105;
  /** RegularExpression Id. */
  int CONST = 106;
  /** RegularExpression Id. */
  int LET = 107;
  /** RegularExpression Id. */
  int VAR = 108;
  /** RegularExpression Id. */
  int STATIC = 109;
  /** RegularExpression Id. */
  int FINAL = 110;
  /** RegularExpression Id. */
  int ABSTRACT = 111;
  /** RegularExpression Id. */
  int VIRTUAL = 112;
  /** RegularExpression Id. */
  int SEALED = 113;
  /** RegularExpression Id. */
  int IMMUTABLE = 114;
  /** RegularExpression Id. */
  int MUTABLE = 115;
  /** RegularExpression Id. */
  int VOLATILE = 116;
  /** RegularExpression Id. */
  int EXTERN = 117;
  /** RegularExpression Id. */
  int REGISTER = 118;
  /** RegularExpression Id. */
  int OVERRIDE = 119;
  /** RegularExpression Id. */
  int EXPLICIT = 120;
  /** RegularExpression Id. */
  int IMPLICIT = 121;
  /** RegularExpression Id. */
  int IF = 122;
  /** RegularExpression Id. */
  int ELSE = 123;
  /** RegularExpression Id. */
  int ELIF = 124;
  /** RegularExpression Id. */
  int SWITCH = 125;
  /** RegularExpression Id. */
  int CASE = 126;
  /** RegularExpression Id. */
  int DEFAULT_CASE = 127;
  /** RegularExpression Id. */
  int WHILE = 128;
  /** RegularExpression Id. */
  int DO_WHILE = 129;
  /** RegularExpression Id. */
  int FOR = 130;
  /** RegularExpression Id. */
  int FOREACH = 131;
  /** RegularExpression Id. */
  int LOOP = 132;
  /** RegularExpression Id. */
  int UNTIL = 133;
  /** RegularExpression Id. */
  int MATCH = 134;
  /** RegularExpression Id. */
  int WHEN = 135;
  /** RegularExpression Id. */
  int OF = 136;
  /** RegularExpression Id. */
  int IN = 137;
  /** RegularExpression Id. */
  int BREAK = 138;
  /** RegularExpression Id. */
  int CONTINUE = 139;
  /** RegularExpression Id. */
  int RETURN = 140;
  /** RegularExpression Id. */
  int YIELD = 141;
  /** RegularExpression Id. */
  int THROW = 142;
  /** RegularExpression Id. */
  int RETHROW = 143;
  /** RegularExpression Id. */
  int GOTO = 144;
  /** RegularExpression Id. */
  int EXIT = 145;
  /** RegularExpression Id. */
  int TRY = 146;
  /** RegularExpression Id. */
  int CATCH = 147;
  /** RegularExpression Id. */
  int FINALLY = 148;
  /** RegularExpression Id. */
  int THROWS = 149;
  /** RegularExpression Id. */
  int EXCEPTION = 150;
  /** RegularExpression Id. */
  int ASSERT = 151;
  /** RegularExpression Id. */
  int ENSURE = 152;
  /** RegularExpression Id. */
  int ASYNC = 153;
  /** RegularExpression Id. */
  int AWAIT = 154;
  /** RegularExpression Id. */
  int SPAWN = 155;
  /** RegularExpression Id. */
  int THREAD = 156;
  /** RegularExpression Id. */
  int SYNC = 157;
  /** RegularExpression Id. */
  int LOCK = 158;
  /** RegularExpression Id. */
  int MUTEX = 159;
  /** RegularExpression Id. */
  int FUNCTION = 160;
  /** RegularExpression Id. */
  int METHOD = 161;
  /** RegularExpression Id. */
  int PROCEDURE = 162;
  /** RegularExpression Id. */
  int CONSTRUCTOR = 163;
  /** RegularExpression Id. */
  int DESTRUCTOR = 164;
  /** RegularExpression Id. */
  int OPERATOR = 165;
  /** RegularExpression Id. */
  int GETTER = 166;
  /** RegularExpression Id. */
  int SETTER = 167;
  /** RegularExpression Id. */
  int PROPERTY = 168;
  /** RegularExpression Id. */
  int NEW = 169;
  /** RegularExpression Id. */
  int DELETE = 170;
  /** RegularExpression Id. */
  int FREE = 171;
  /** RegularExpression Id. */
  int MALLOC = 172;
  /** RegularExpression Id. */
  int CALLOC = 173;
  /** RegularExpression Id. */
  int REALLOC = 174;
  /** RegularExpression Id. */
  int ALLOCATE = 175;
  /** RegularExpression Id. */
  int GC = 176;
  /** RegularExpression Id. */
  int STAR = 177;
  /** RegularExpression Id. */
  int AMP = 178;
  /** RegularExpression Id. */
  int MUT_REF = 179;
  /** RegularExpression Id. */
  int UNIQUE_PTR = 180;
  /** RegularExpression Id. */
  int SHARED_PTR = 181;
  /** RegularExpression Id. */
  int SMART_PTR = 182;
  /** RegularExpression Id. */
  int IMPORT = 183;
  /** RegularExpression Id. */
  int EXPORT = 184;
  /** RegularExpression Id. */
  int MODULE = 185;
  /** RegularExpression Id. */
  int NAMESPACE = 186;
  /** RegularExpression Id. */
  int USING = 187;
  /** RegularExpression Id. */
  int FROM = 188;
  /** RegularExpression Id. */
  int INCLUDE = 189;
  /** RegularExpression Id. */
  int REQUIRE_JS = 190;
  /** RegularExpression Id. */
  int TEMPLATE = 191;
  /** RegularExpression Id. */
  int WHERE = 192;
  /** RegularExpression Id. */
  int TYPE = 193;
  /** RegularExpression Id. */
  int TYPEOF = 194;
  /** RegularExpression Id. */
  int INSTANCEOF = 195;
  /** RegularExpression Id. */
  int AS = 196;
  /** RegularExpression Id. */
  int IS = 197;
  /** RegularExpression Id. */
  int SIZEOF = 198;
  /** RegularExpression Id. */
  int THIS = 199;
  /** RegularExpression Id. */
  int SELF = 200;
  /** RegularExpression Id. */
  int SUPER = 201;
  /** RegularExpression Id. */
  int BASE = 202;
  /** RegularExpression Id. */
  int PARENT = 203;
  /** RegularExpression Id. */
  int ROOT = 204;
  /** RegularExpression Id. */
  int LOCAL = 205;
  /** RegularExpression Id. */
  int GLOBAL = 206;
  /** RegularExpression Id. */
  int AT = 207;
  /** RegularExpression Id. */
  int METADATA = 208;
  /** RegularExpression Id. */
  int SELECT = 209;
  /** RegularExpression Id. */
  int FROM_SQL = 210;
  /** RegularExpression Id. */
  int WHERE_SQL = 211;
  /** RegularExpression Id. */
  int JOIN_SQL = 212;
  /** RegularExpression Id. */
  int ON_SQL = 213;
  /** RegularExpression Id. */
  int GROUP_BY_SQL = 214;
  /** RegularExpression Id. */
  int ORDER_BY_SQL = 215;
  /** RegularExpression Id. */
  int HAVING = 216;
  /** RegularExpression Id. */
  int INSERT = 217;
  /** RegularExpression Id. */
  int INTO = 218;
  /** RegularExpression Id. */
  int VALUES = 219;
  /** RegularExpression Id. */
  int UPDATE = 220;
  /** RegularExpression Id. */
  int SET_SQL = 221;
  /** RegularExpression Id. */
  int DELETE_SQL = 222;
  /** RegularExpression Id. */
  int DISTINCT = 223;
  /** RegularExpression Id. */
  int UNION = 224;
  /** RegularExpression Id. */
  int INTERSECT = 225;
  /** RegularExpression Id. */
  int EXCEPT = 226;
  /** RegularExpression Id. */
  int LIMIT = 227;
  /** RegularExpression Id. */
  int OFFSET = 228;
  /** RegularExpression Id. */
  int INNER_JOIN = 229;
  /** RegularExpression Id. */
  int LEFT_JOIN = 230;
  /** RegularExpression Id. */
  int RIGHT_JOIN = 231;
  /** RegularExpression Id. */
  int FULL_JOIN = 232;
  /** RegularExpression Id. */
  int CROSS_JOIN = 233;
  /** RegularExpression Id. */
  int HTTP_GET = 234;
  /** RegularExpression Id. */
  int POST = 235;
  /** RegularExpression Id. */
  int PUT = 236;
  /** RegularExpression Id. */
  int PATCH = 237;
  /** RegularExpression Id. */
  int DELETE_HTTP = 238;
  /** RegularExpression Id. */
  int HEAD = 239;
  /** RegularExpression Id. */
  int OPTIONS = 240;
  /** RegularExpression Id. */
  int HTTP = 241;
  /** RegularExpression Id. */
  int HTTPS = 242;
  /** RegularExpression Id. */
  int REST = 243;
  /** RegularExpression Id. */
  int GRAPHQL = 244;
  /** RegularExpression Id. */
  int WEBSOCKET = 245;
  /** RegularExpression Id. */
  int CONTROLLER = 246;
  /** RegularExpression Id. */
  int SERVICE = 247;
  /** RegularExpression Id. */
  int REPOSITORY = 248;
  /** RegularExpression Id. */
  int MIDDLEWARE = 249;
  /** RegularExpression Id. */
  int ROUTE = 250;
  /** RegularExpression Id. */
  int ENDPOINT = 251;
  /** RegularExpression Id. */
  int INT = 252;
  /** RegularExpression Id. */
  int FLOAT = 253;
  /** RegularExpression Id. */
  int FLOAT2 = 254;
  /** RegularExpression Id. */
  int FLOAT3 = 255;
  /** RegularExpression Id. */
  int SCIENCE = 256;
  /** RegularExpression Id. */
  int HEX = 257;
  /** RegularExpression Id. */
  int OCTAL = 258;
  /** RegularExpression Id. */
  int BINARY = 259;
  /** RegularExpression Id. */
  int NAN = 260;
  /** RegularExpression Id. */
  int INFINITY = 261;
  /** RegularExpression Id. */
  int STRING_LIT = 262;
  /** RegularExpression Id. */
  int CHAR_LIT = 263;
  /** RegularExpression Id. */
  int ESCAPE_CHAR = 264;
  /** RegularExpression Id. */
  int TEMPLATE_STRING = 265;
  /** RegularExpression Id. */
  int RAW_STRING = 266;
  /** RegularExpression Id. */
  int MULTILINE_STRING = 267;
  /** RegularExpression Id. */
  int PREPROC = 268;
  /** RegularExpression Id. */
  int INCLUDE_DIR = 269;
  /** RegularExpression Id. */
  int DEFINE = 270;
  /** RegularExpression Id. */
  int IFDEF = 271;
  /** RegularExpression Id. */
  int IFNDEF = 272;
  /** RegularExpression Id. */
  int ENDIF = 273;
  /** RegularExpression Id. */
  int PRAGMA = 274;
  /** RegularExpression Id. */
  int SHEBANG = 275;
  /** RegularExpression Id. */
  int LINE_COMMENT = 276;
  /** RegularExpression Id. */
  int BLOCK_COMMENT = 277;
  /** RegularExpression Id. */
  int DOC_COMMENT = 278;
  /** RegularExpression Id. */
  int IDENTIFIER = 279;
  /** RegularExpression Id. */
  int GLOBAL_ID = 280;
  /** RegularExpression Id. */
  int PRIVATE_ID = 281;
  /** RegularExpression Id. */
  int INTERNAL_ID = 282;
  /** RegularExpression Id. */
  int SPECIAL_VAR = 283;
  /** RegularExpression Id. */
  int CONTEXT_VAR = 284;
  /** RegularExpression Id. */
  int TYPE_PARAM = 285;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"<<=\"",
    "\">>=\"",
    "\"**=\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"%=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
    "\"=\"",
    "\"**\"",
    "\"//\"",
    "\"+\"",
    "\"-\"",
    "\"/\"",
    "\"%\"",
    "\"++\"",
    "\"--\"",
    "\"===\"",
    "\"!==\"",
    "\"<=\"",
    "\">=\"",
    "\"==\"",
    "\"!=\"",
    "\"<<\"",
    "\">>>\"",
    "\">>\"",
    "\"<\"",
    "\">\"",
    "\"&&\"",
    "\"||\"",
    "\"!\"",
    "\"^\"",
    "\"~\"",
    "\"\\\\?\\\\?\"",
    "\"\\\\?\\\\.\"",
    "\"...\"",
    "\"..\"",
    "\"\\\\?\"",
    "\":\"",
    "\"|\"",
    "\".\"",
    "\",\"",
    "\";\"",
    "\";;\"",
    "\"_\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"int8\"",
    "\"int16\"",
    "\"int32\"",
    "\"int64\"",
    "\"uint8\"",
    "\"uint16\"",
    "\"uint32\"",
    "\"uint64\"",
    "\"float32\"",
    "\"float64\"",
    "\"integer\"",
    "\"number\"",
    "\"decimal\"",
    "\"double\"",
    "\"char\"",
    "\"rune\"",
    "\"byte\"",
    "\"string\"",
    "\"bool\"",
    "\"any\"",
    "\"void\"",
    "\"null\"",
    "\"undefined\"",
    "\"never\"",
    "\"unknown\"",
    "\"none\"",
    "\"true\"",
    "\"false\"",
    "\"array\"",
    "\"list\"",
    "\"tuple\"",
    "\"map\"",
    "\"dict\"",
    "\"object\"",
    "\"record\"",
    "\"struct\"",
    "\"enum\"",
    "\"interface\"",
    "\"class\"",
    "\"public\"",
    "\"private\"",
    "\"protected\"",
    "\"internal\"",
    "\"readonly\"",
    "\"writeonly\"",
    "\"friend\"",
    "\"package\"",
    "\"const\"",
    "\"let\"",
    "\"var\"",
    "\"static\"",
    "\"final\"",
    "\"abstract\"",
    "\"virtual\"",
    "\"sealed\"",
    "\"immutable\"",
    "\"mutable\"",
    "\"volatile\"",
    "\"extern\"",
    "\"register\"",
    "\"override\"",
    "\"explicit\"",
    "\"implicit\"",
    "\"if\"",
    "\"else\"",
    "\"elif\"",
    "\"switch\"",
    "\"case\"",
    "\"default\"",
    "\"while\"",
    "\"do\"",
    "\"for\"",
    "\"foreach\"",
    "\"loop\"",
    "\"until\"",
    "\"match\"",
    "\"when\"",
    "\"of\"",
    "\"in\"",
    "\"break\"",
    "\"continue\"",
    "\"return\"",
    "\"yield\"",
    "\"throw\"",
    "\"rethrow\"",
    "\"goto\"",
    "\"exit\"",
    "\"try\"",
    "\"catch\"",
    "\"finally\"",
    "\"throws\"",
    "\"exception\"",
    "\"assert\"",
    "\"ensure\"",
    "\"async\"",
    "\"await\"",
    "\"spawn\"",
    "\"thread\"",
    "\"sync\"",
    "\"lock\"",
    "\"mutex\"",
    "\"function\"",
    "\"method\"",
    "\"procedure\"",
    "\"constructor\"",
    "\"destructor\"",
    "\"operator\"",
    "\"get\"",
    "\"set\"",
    "\"property\"",
    "\"new\"",
    "\"delete\"",
    "\"free\"",
    "\"malloc\"",
    "\"calloc\"",
    "\"realloc\"",
    "\"allocate\"",
    "\"gc\"",
    "\"*\"",
    "\"&\"",
    "\"&mut\"",
    "\"unique_ptr\"",
    "\"shared_ptr\"",
    "\"Box\"",
    "\"import\"",
    "\"export\"",
    "\"module\"",
    "\"namespace\"",
    "\"using\"",
    "\"from\"",
    "\"include\"",
    "\"require\"",
    "\"template\"",
    "\"where\"",
    "\"type\"",
    "\"typeof\"",
    "\"instanceof\"",
    "\"as\"",
    "\"is\"",
    "\"sizeof\"",
    "\"this\"",
    "\"self\"",
    "\"super\"",
    "\"base\"",
    "\"parent\"",
    "\"root\"",
    "\"local\"",
    "\"global\"",
    "\"@\"",
    "\"metadata\"",
    "\"select\"",
    "\"from_sql\"",
    "\"where_sql\"",
    "\"join_sql\"",
    "\"on_sql\"",
    "\"group_by\"",
    "\"order_by\"",
    "\"having\"",
    "\"insert\"",
    "\"into\"",
    "\"values\"",
    "\"update\"",
    "\"set_sql\"",
    "\"delete_sql\"",
    "\"distinct\"",
    "\"union\"",
    "\"intersect\"",
    "\"except\"",
    "\"limit\"",
    "\"offset\"",
    "\"inner_join\"",
    "\"left_join\"",
    "\"right_join\"",
    "\"full_join\"",
    "\"cross_join\"",
    "\"get_\"",
    "\"post\"",
    "\"put\"",
    "\"patch\"",
    "\"http_delete\"",
    "\"head\"",
    "\"options\"",
    "\"http\"",
    "\"https\"",
    "\"rest\"",
    "\"graphql\"",
    "\"websocket\"",
    "\"controller\"",
    "\"service\"",
    "\"repository\"",
    "\"middleware\"",
    "\"route\"",
    "\"endpoint\"",
    "<INT>",
    "<FLOAT>",
    "<FLOAT2>",
    "<FLOAT3>",
    "<SCIENCE>",
    "<HEX>",
    "<OCTAL>",
    "<BINARY>",
    "\"NaN\"",
    "\"Infinity\"",
    "<STRING_LIT>",
    "<CHAR_LIT>",
    "<ESCAPE_CHAR>",
    "<TEMPLATE_STRING>",
    "<RAW_STRING>",
    "<MULTILINE_STRING>",
    "<PREPROC>",
    "\"#include\"",
    "\"#define\"",
    "\"#ifdef\"",
    "\"#ifndef\"",
    "\"#endif\"",
    "\"#pragma\"",
    "<SHEBANG>",
    "<LINE_COMMENT>",
    "<BLOCK_COMMENT>",
    "<DOC_COMMENT>",
    "<IDENTIFIER>",
    "<GLOBAL_ID>",
    "<PRIVATE_ID>",
    "<INTERNAL_ID>",
    "<SPECIAL_VAR>",
    "<CONTEXT_VAR>",
    "<TYPE_PARAM>",
    "\"ASC\"",
    "\"DESC\"",
    "\"extends\"",
    "\"implements\"",
  };

}
